### ISSUE TITLE
Archlinux

### ISSUE THREAD

**Issue by loglyy** [pnegre/python-whiteboard#15]
Hi,
I'm a french teacher and I want to use python-whiteboard. I've tried to install it on archlinux. Problem is that the program do not start up.
Do you have a solution? I've seen that someone have tried to make a PKGBUILD but this one is not the good one.
Thnaks for your help.

**Comment by pnegre** [comment]
Try to start the program from the command line and paste the error messages here...

**Comment by loglyy** [comment]
Hi,
Thanks for the reply. Here is the error message of the command line. I've already try to put parentheses but I don't know if I did it the right way.

[logly@yoga213 ~]$ /usr/bin/python-whiteboard
  File "/usr/bin/python-whiteboard", line 11
    print "Can't find " + STUFFDIR
                      ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by pnegre** [comment]
That's because this program is not compatible with "python3". You need python2 to run it. I don't use archlinux, so I cannot give much directions. Try this: http://stackoverflow.com/questions/15400985/how-to-completely-replace-python-3-with-python-2-in-arch-linux

**Comment by loglyy** [comment]
It was the good solution.
Thanks a lot.
